enum BookCategory {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  AUTOBIOGRAPHY = 'Autobiography',
  BIOGRAPY = 'Biography',
  CLASSIC = 'Classic',
  COMIC = 'Comic',
  CRIME = 'Crime',
  DRAMA = 'Drama',
  EPIC = 'Epic',
  ESSAY = 'Essay',
  FAIRYTALE = 'Fairytale',
  FANTACY = 'Fantacy',
  FICTION = 'Fiction',
  HISTORY = 'Fistory',
  HORROR = 'Horror',
  JOURNAL = 'Journal',
  MEMOIR = 'Memoir',
  MYSTERY = 'Mystery',
  POETRY = 'Poetry',
  ROMANCE = 'Romance',
  SCIENCE = 'Science',
  SCIENCE_FICTION = 'Science fiction',
  SHORT_STORY = 'Short story',
  SUSPENSE = 'Suspense',
  TECHNOLOGY = 'Technology',
  THRILLER = 'Thriller',
}

export default BookCategory
